[package]
name = "owasm-vm"
version = "0.1.13"
authors = ["Band Protocol <connect@bandprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/bandprotocol/owasm/tree/master/packages/vm"
description = "Oracle script VM runtime"
readme = "README.md"

[dependencies]
assert_matches = "1.3.0"
hex = "0.4"
parity-wasm = "0.41"
pwasm-utils = "0.12"
wasmer = { version = "1.0.2", default-features = false, features = ["jit", "singlepass", "compiler"] }
tempfile = "3.1.0"
clru = "0.2.0"
cosmwasm-vm = "0.13.2"
